import React, { useState, useEffect } from 'react';
import { BookData } from './types/book';
import DigitalLibrary from './components/DigitalLibrary';
import Dashboard from './components/Dashboard';
import LoginModal from './components/LoginModal';

function App() {
  const [currentPage, setCurrentPage] = useState('library');
  const [currentUser, setCurrentUser] = useState<any>(null);
  const [isLoginModalOpen, setIsLoginModalOpen] = useState(false);
  const [books, setBooks] = useState<BookData[]>([
    {
      id: 1,
      title: "Matematika Kelas X - Kurikulum Merdeka",
      subtitle: "Panduan Lengkap Matematika SMA",
      author: "Dr. Ahmad Susanto, M.Pd",
      coAuthor: "Prof. Dr. Siti Aminah",
      editor: "Dr. Budi Hartono",
      translator: "",
      illustrator: "Andi Grafis Studio",
      category: "500",
      publisher: "Erlangga",
      publicationPlace: "Jakarta",
      publicationYear: "2023",
      edition: "Edisi Revisi",
      isbn: "978-602-298-123-4",
      issn: "",
      callNumber: "510.07 SUS m",
      deweyNumber: "510.07",
      pages: "324",
      dimensions: "25 x 18 cm",
      language: "Indonesia",
      series: "Kurikulum Merdeka",
      volume: "1",
      notes: "Dilengkapi dengan QR Code untuk materi digital",
      subjects: ["Matematika", "Pendidikan", "Kurikulum Merdeka"],
      physicalDescription: "Buku dengan sampul soft cover, kertas HVS 70gsm, full color",
      contentType: "Teks",
      mediaType: "Tanpa Mediasi",
      carrierType: "Volume",
      location: "Rak A-1, Lantai 1",
      copyNumber: 5,
      barcode: "2024001001",
      price: "125000",
      source: "Pembelian",
      acquisitionDate: "2024-01-15",
      condition: "Baik",
      status: "Tersedia",
      abstract: "Buku matematika untuk kelas X yang disusun berdasarkan kurikulum merdeka dengan pendekatan pembelajaran yang inovatif dan menyenangkan.",
      cover: "https://images.pexels.com/photos/159711/books-bookstore-book-reading-159711.jpeg?auto=compress&cs=tinysrgb&w=300",
      digitalFiles: ["PDF", "E-Book", "Video"]
    },
    {
      id: 2,
      title: "Sejarah Indonesia Modern - Dari Kemerdekaan hingga Reformasi",
      subtitle: "Perjalanan Bangsa Indonesia",
      author: "Prof. Dr. Sartono Kartodirdjo",
      coAuthor: "Dr. Bambang Purwanto",
      editor: "Prof. Dr. Asvi Warman Adam",
      translator: "",
      illustrator: "Tim Ilustrasi Sejarah",
      category: "900",
      publisher: "Gramedia Pustaka Utama",
      publicationPlace: "Jakarta",
      publicationYear: "2022",
      edition: "Edisi Ketiga",
      isbn: "978-602-06-456-7",
      issn: "",
      callNumber: "959.8 KAR s",
      deweyNumber: "959.8",
      pages: "456",
      dimensions: "23 x 15 cm",
      language: "Indonesia",
      series: "Sejarah Nusantara",
      volume: "2",
      notes: "Dilengkapi dengan foto-foto sejarah dan peta",
      subjects: ["Sejarah", "Indonesia", "Politik", "Kemerdekaan"],
      physicalDescription: "Hard cover dengan dust jacket, kertas art paper, ilustrasi berwarna",
      contentType: "Teks",
      mediaType: "Tanpa Mediasi",
      carrierType: "Volume",
      location: "Rak B-3, Lantai 2",
      copyNumber: 3,
      barcode: "2024001002",
      price: "89000",
      source: "Hibah",
      acquisitionDate: "2024-02-10",
      condition: "Sangat Baik",
      status: "Dipinjam",
      abstract: "Buku ini mengulas perjalanan sejarah Indonesia modern dari masa kemerdekaan hingga era reformasi dengan analisis mendalam dan objektif.",
      cover: "https://images.pexels.com/photos/1370295/pexels-photo-1370295.jpeg?auto=compress&cs=tinysrgb&w=300",
      digitalFiles: ["PDF", "Flipbook"]
    },
    {
      id: 3,
      title: "Fisika Dasar - Mekanika dan Termodinamika",
      subtitle: "Konsep dan Aplikasi",
      author: "Dr. Bambang Ruwanto, M.Si",
      coAuthor: "Dr. Yohanes Surya",
      editor: "Prof. Dr. Mikrajuddin Abdullah",
      translator: "",
      illustrator: "Physics Illustration Team",
      category: "500",
      publisher: "Kanisius",
      publicationPlace: "Yogyakarta",
      publicationYear: "2023",
      edition: "Edisi Kedua",
      isbn: "978-979-21-789-0",
      issn: "",
      callNumber: "530 RUW f",
      deweyNumber: "530",
      pages: "398",
      dimensions: "24 x 17 cm",
      language: "Indonesia",
      series: "Fisika untuk SMA",
      volume: "1",
      notes: "Dilengkapi dengan simulasi online dan video eksperimen",
      subjects: ["Fisika", "Sains", "Mekanika", "Termodinamika"],
      physicalDescription: "Soft cover, kertas book paper, diagram dan ilustrasi berwarna",
      contentType: "Teks",
      mediaType: "Tanpa Mediasi",
      carrierType: "Volume",
      location: "Rak C-2, Lantai 1",
      copyNumber: 4,
      barcode: "2024001003",
      price: "145000",
      source: "Pembelian",
      acquisitionDate: "2024-01-20",
      condition: "Baik",
      status: "Tersedia",
      abstract: "Buku fisika dasar yang membahas konsep mekanika dan termodinamika dengan pendekatan yang mudah dipahami siswa SMA.",
      cover: "https://images.pexels.com/photos/1029141/pexels-photo-1029141.jpeg?auto=compress&cs=tinysrgb&w=300",
      digitalFiles: ["PDF", "Video", "E-Book"]
    },
    {
      id: 4,
      title: "Bahasa Indonesia Kelas XI - Komunikasi Efektif",
      subtitle: "Keterampilan Berbahasa untuk Masa Depan",
      author: "Dra. Sri Wahyuni, M.Pd",
      coAuthor: "Dr. Dendy Sugono",
      editor: "Prof. Dr. Hasan Alwi",
      translator: "",
      illustrator: "Creative Design Team",
      category: "400",
      publisher: "Tiga Serangkai",
      publicationPlace: "Solo",
      publicationYear: "2023",
      edition: "Edisi Terbaru",
      isbn: "978-602-250-234-5",
      issn: "",
      callNumber: "499.221 WAH b",
      deweyNumber: "499.221",
      pages: "287",
      dimensions: "25 x 17 cm",
      language: "Indonesia",
      series: "Bahasa Indonesia SMA",
      volume: "2",
      notes: "Dilengkapi dengan audio pronunciation dan video pembelajaran",
      subjects: ["Bahasa Indonesia", "Komunikasi", "Sastra", "Linguistik"],
      physicalDescription: "Soft cover, kertas HVS, ilustrasi dan foto berwarna",
      contentType: "Teks",
      mediaType: "Tanpa Mediasi",
      carrierType: "Volume",
      location: "Rak A-5, Lantai 1",
      copyNumber: 6,
      barcode: "2024001004",
      price: "98000",
      source: "Pembelian",
      acquisitionDate: "2024-02-05",
      condition: "Baik",
      status: "Tersedia",
      abstract: "Buku bahasa Indonesia yang fokus pada pengembangan keterampilan komunikasi efektif untuk siswa kelas XI.",
      cover: "https://images.pexels.com/photos/1370295/pexels-photo-1370295.jpeg?auto=compress&cs=tinysrgb&w=300",
      digitalFiles: ["PDF", "Audio Book"]
    },
    {
      id: 5,
      title: "Kimia Organik - Struktur dan Reaksi",
      subtitle: "Dasar-dasar Kimia Organik",
      author: "Prof. Dr. Mulyono Hadi",
      coAuthor: "Dr. Fessenden",
      editor: "Dr. Buchari",
      translator: "Dr. Aloysius Hadyana Pudjaatmaka",
      illustrator: "Chemistry Graphics Lab",
      category: "500",
      publisher: "ITB Press",
      publicationPlace: "Bandung",
      publicationYear: "2022",
      edition: "Edisi Kelima",
      isbn: "978-602-440-567-8",
      issn: "",
      callNumber: "547 MUL k",
      deweyNumber: "547",
      pages: "512",
      dimensions: "26 x 19 cm",
      language: "Indonesia",
      series: "Kimia untuk Perguruan Tinggi",
      volume: "1",
      notes: "Terjemahan dari buku Fessenden, dilengkapi dengan soal latihan",
      subjects: ["Kimia", "Kimia Organik", "Sains", "Molekul"],
      physicalDescription: "Hard cover, kertas art paper, diagram molekul berwarna",
      contentType: "Teks",
      mediaType: "Tanpa Mediasi",
      carrierType: "Volume",
      location: "Rak D-1, Lantai 2",
      copyNumber: 2,
      barcode: "2024001005",
      price: "167000",
      source: "Pembelian",
      acquisitionDate: "2024-01-08",
      condition: "Cukup",
      status: "Perawatan",
      abstract: "Buku kimia organik yang membahas struktur molekul organik dan reaksi-reaksi kimia dengan pendekatan sistematis.",
      cover: "https://images.pexels.com/photos/159711/books-bookstore-book-reading-159711.jpeg?auto=compress&cs=tinysrgb&w=300",
      digitalFiles: ["PDF", "Video", "Flipbook"]
    },
    {
      id: 6,
      title: "Biologi Sel dan Molekuler - Dasar-dasar Kehidupan",
      subtitle: "Eksplorasi Dunia Mikroskopis",
      author: "Dr. Siti Rahayu, M.Si",
      coAuthor: "Prof. Dr. Campbell",
      editor: "Dr. Sutarno",
      translator: "Dr. Damandiri",
      illustrator: "BioArt Illustration",
      category: "500",
      publisher: "Universitas Indonesia Press",
      publicationPlace: "Jakarta",
      publicationYear: "2023",
      edition: "Edisi Keempat",
      isbn: "978-979-456-890-1",
      issn: "",
      callNumber: "571.6 RAH b",
      deweyNumber: "571.6",
      pages: "423",
      dimensions: "25 x 18 cm",
      language: "Indonesia",
      series: "Biologi Modern",
      volume: "1",
      notes: "Adaptasi dari Campbell Biology, dilengkapi dengan foto mikroskopis",
      subjects: ["Biologi", "Sel", "Molekuler", "Genetika"],
      physicalDescription: "Hard cover, kertas glossy, foto mikroskopis berwarna",
      contentType: "Teks",
      mediaType: "Tanpa Mediasi",
      carrierType: "Volume",
      location: "Rak C-4, Lantai 2",
      copyNumber: 3,
      barcode: "2024001006",
      price: "134000",
      source: "Pembelian",
      acquisitionDate: "2024-02-12",
      condition: "Sangat Baik",
      status: "Tersedia",
      abstract: "Buku biologi yang mengeksplorasi dunia sel dan molekuler dengan pendekatan modern dan ilustrasi yang menarik.",
      cover: "https://images.pexels.com/photos/1029141/pexels-photo-1029141.jpeg?auto=compress&cs=tinysrgb&w=300",
      digitalFiles: ["PDF", "Video"]
    },
    {
      id: 7,
      title: "Ekonomi Makro - Teori dan Aplikasi",
      subtitle: "Memahami Perekonomian Nasional",
      author: "Dr. Budi Santoso, S.E., M.M",
      coAuthor: "Prof. Dr. Mankiw",
      editor: "Dr. Mulyadi",
      translator: "Dr. Chriswan Sungkono",
      illustrator: "Economic Charts Studio",
      category: "300",
      publisher: "Salemba Empat",
      publicationPlace: "Jakarta",
      publicationYear: "2022",
      edition: "Edisi Ketujuh",
      isbn: "978-602-5251-23-4",
      issn: "",
      callNumber: "339 SAN e",
      deweyNumber: "339",
      pages: "367",
      dimensions: "24 x 16 cm",
      language: "Indonesia",
      series: "Ekonomi untuk SMA",
      volume: "2",
      notes: "Terjemahan dari Mankiw's Macroeconomics, disesuaikan dengan kondisi Indonesia",
      subjects: ["Ekonomi", "Makro", "Teori Ekonomi", "Kebijakan"],
      physicalDescription: "Soft cover, kertas book paper, grafik dan chart berwarna",
      contentType: "Teks",
      mediaType: "Tanpa Mediasi",
      carrierType: "Volume",
      location: "Rak E-2, Lantai 1",
      copyNumber: 4,
      barcode: "2024001007",
      price: "112000",
      source: "Pembelian",
      acquisitionDate: "2024-01-25",
      condition: "Baik",
      status: "Dipinjam",
      abstract: "Buku ekonomi makro yang membahas teori dan aplikasi dalam konteks perekonomian Indonesia dan global.",
      cover: "https://images.pexels.com/photos/1370295/pexels-photo-1370295.jpeg?auto=compress&cs=tinysrgb&w=300",
      digitalFiles: ["PDF", "E-Book"]
    },
    {
      id: 8,
      title: "Sosiologi Pendidikan - Perspektif Kontemporer",
      subtitle: "Analisis Sosial dalam Pendidikan",
      author: "Prof. Dr. Nanang Martono",
      coAuthor: "Dr. Diane Reay",
      editor: "Dr. Ida Bagus Mantra",
      translator: "",
      illustrator: "Social Graphics Team",
      category: "300",
      publisher: "RajaGrafindo Persada",
      publicationPlace: "Jakarta",
      publicationYear: "2023",
      edition: "Edisi Kedua",
      isbn: "978-602-425-678-9",
      issn: "",
      callNumber: "370.19 MAR s",
      deweyNumber: "370.19",
      pages: "298",
      dimensions: "23 x 15 cm",
      language: "Indonesia",
      series: "Sosiologi Kontemporer",
      volume: "1",
      notes: "Dilengkapi dengan studi kasus pendidikan di Indonesia",
      subjects: ["Sosiologi", "Pendidikan", "Masyarakat", "Sosial"],
      physicalDescription: "Soft cover, kertas HVS, diagram dan tabel",
      contentType: "Teks",
      mediaType: "Tanpa Mediasi",
      carrierType: "Volume",
      location: "Rak F-1, Lantai 2",
      copyNumber: 2,
      barcode: "2024001008",
      price: "87000",
      source: "Pembelian",
      acquisitionDate: "2024-02-18",
      condition: "Baik",
      status: "Tersedia",
      abstract: "Analisis mendalam tentang hubungan antara pendidikan dan masyarakat dari perspektif sosiologi kontemporer.",
      cover: "https://images.pexels.com/photos/1370295/pexels-photo-1370295.jpeg?auto=compress&cs=tinysrgb&w=300",
      digitalFiles: ["PDF"]
    },
    {
      id: 9,
      title: "Geografi Indonesia - Fisik dan Manusia",
      subtitle: "Kekayaan Alam dan Budaya Nusantara",
      author: "Dr. Aris Munandar, M.Si",
      coAuthor: "Prof. Dr. Bintarto",
      editor: "Dr. Surastopo Hadisumarno",
      translator: "",
      illustrator: "GeoMap Illustration",
      category: "900",
      publisher: "Yudhistira",
      publicationPlace: "Jakarta",
      publicationYear: "2023",
      edition: "Edisi Revisi",
      isbn: "978-602-04-789-0",
      issn: "",
      callNumber: "915.98 MUN g",
      deweyNumber: "915.98",
      pages: "445",
      dimensions: "25 x 18 cm",
      language: "Indonesia",
      series: "Geografi Nusantara",
      volume: "1",
      notes: "Dilengkapi dengan peta terbaru dan foto satelit",
      subjects: ["Geografi", "Indonesia", "Fisik", "Demografi"],
      physicalDescription: "Hard cover, kertas art paper, peta dan foto berwarna",
      contentType: "Teks",
      mediaType: "Tanpa Mediasi",
      carrierType: "Volume",
      location: "Rak B-5, Lantai 1",
      copyNumber: 5,
      barcode: "2024001009",
      price: "156000",
      source: "Pembelian",
      acquisitionDate: "2024-01-30",
      condition: "Sangat Baik",
      status: "Tersedia",
      abstract: "Eksplorasi komprehensif tentang geografi Indonesia meliputi aspek fisik dan manusia dengan data terkini.",
      cover: "https://images.pexels.com/photos/1029141/pexels-photo-1029141.jpeg?auto=compress&cs=tinysrgb&w=300",
      digitalFiles: ["PDF", "E-Book"]
    },
    {
      id: 10,
      title: "Psikologi Perkembangan - Anak dan Remaja",
      subtitle: "Memahami Tahap Perkembangan",
      author: "Dr. Rita Eka Izzaty, M.Si",
      coAuthor: "Prof. Dr. Santrock",
      editor: "Dr. Siti Partini Suardiman",
      translator: "Dr. Benedictine Widyasinta",
      illustrator: "Psychology Visual Team",
      category: "100",
      publisher: "UNY Press",
      publicationPlace: "Yogyakarta",
      publicationYear: "2022",
      edition: "Edisi Ketiga",
      isbn: "978-602-498-123-5",
      issn: "",
      callNumber: "155.4 IZZ p",
      deweyNumber: "155.4",
      pages: "334",
      dimensions: "23 x 15 cm",
      language: "Indonesia",
      series: "Psikologi Pendidikan",
      volume: "1",
      notes: "Adaptasi dari Santrock's Child Development, disesuaikan dengan konteks Indonesia",
      subjects: ["Psikologi", "Perkembangan", "Anak", "Remaja"],
      physicalDescription: "Soft cover, kertas book paper, diagram perkembangan",
      contentType: "Teks",
      mediaType: "Tanpa Mediasi",
      carrierType: "Volume",
      location: "Rak G-3, Lantai 2",
      copyNumber: 3,
      barcode: "2024001010",
      price: "95000",
      source: "Hibah",
      acquisitionDate: "2024-02-08",
      condition: "Baik",
      status: "Tersedia",
      abstract: "Panduan komprehensif tentang psikologi perkembangan anak dan remaja dengan pendekatan yang mudah dipahami.",
      cover: "https://images.pexels.com/photos/1370295/pexels-photo-1370295.jpeg?auto=compress&cs=tinysrgb&w=300",
      digitalFiles: ["PDF", "E-Book"]
    }
  ]);

  const navigateToDashboard = () => {
    setCurrentPage('dashboard');
  };

  const openLoginModal = () => {
    setIsLoginModalOpen(true);
  };

  const handleLogin = (user: any) => {
    setCurrentUser(user);
    setIsLoginModalOpen(false);
    setCurrentPage('dashboard');
  };

  const handleLogout = () => {
    setCurrentUser(null);
    setCurrentPage('library');
  };

  return (
    <div className="min-h-screen bg-white">
      {currentPage === 'library' && (
        <DigitalLibrary 
          books={books}
          currentUser={currentUser}
          onNavigateToDashboard={navigateToDashboard}
          onOpenLogin={openLoginModal}
        />
      )}
      {currentPage === 'dashboard' && currentUser && (
        <Dashboard 
          user={currentUser} 
          books={books}
          setBooks={setBooks}
          onLogout={handleLogout} 
          onNavigateToLibrary={() => setCurrentPage('library')}
          onNavigateToOPAC={() => setCurrentPage('library')}
        />
      )}
      
      {/* Global Login Modal */}
      <LoginModal 
        isOpen={isLoginModalOpen}
        onClose={() => setIsLoginModalOpen(false)}
        onLogin={handleLogin}
      />
    </div>
  );
}

export default App;